// --- QUESTIONS DATA ---
const QUESTIONS = [
  { id: 1, text: "Your ideal weekend looks like:", options: ["Crafting or DIY projects","Binge-reading or journaling","Learning something new","Hosting a game night"] },
  { id: 2, text: "Your emotional reset button is:", options: ["Classical calm","Soulful blues","Indie vibes","Dance-pop energy"] },
  { id: 3, text: "You’re most drawn to films that are:", options: ["Deep and dramatic","Smart and funny","Mysterious and intense","Fantastical and epic"] },
  { id: 4, text: "Which sport reflects your energy best?", options: ["Strategic and solo (golf, tennis)","Fast and team-based (soccer, basketball)","Intense and focused (martial arts, boxing)","Wild and free (surfing, skiing)"] },
  { id: 5, text: "Your soul food is:", options: ["Mediterranean mezze","Sushi or ramen","Pasta or pastries","Tacos or curry"] },
  { id: 6, text: "You recharge by:", options: ["Hiking remote trails","Exploring historic cities","Lounging at a resort","Chasing festivals and fun"] },
  { id: 7, text: "Your fashion speaks:", options: ["Understated elegance","Bold and artsy","Trendy and expressive","Cozy and chill"] },
  { id: 8, text: "Your bookshelf leans toward:", options: ["Deep philosophy","Page-turning thrillers","Epic fantasy","Real-life stories"] },
  { id: 9, text: "You approach new tech like:", options: ["A curious explorer","A cautious optimist","A skeptical realist","A nostalgic minimalist"] },
  { id: 10, text: "You’re most motivated by:", options: ["Creative freedom","Security and structure","Team collaboration","Making a bold impact"] },
  { id: 11, text: "You learn best through:", options: ["Hands-on trial","Deep reading","Group discussion","Visual demos"] },
  { id: 12, text: "Your ideal hangout is:", options: ["Small and meaningful","Big and buzzing","One-on-one depth","Solo with occasional check-ins"] },
  { id: 13, text: "Your go-to reset is:", options: ["Meditation","Movement","Journaling","Cooking"] },
  { id: 14, text: "You feel most alive in:", options: ["Forests","Mountains","Oceans","Deserts"] },
  { id: 15, text: "You express yourself through:", options: ["Visual art","Music or dance","Theater or storytelling","Digital design"] },
  { id: 16, text: "You’re most articulate when:", options: ["Writing","Speaking","Showing","Doing"] },
  { id: 17, text: "Your guiding principle is:", options: ["Integrity","Compassion","Drive","Curiosity"] },
  { id: 18, text: "You value most in connection:", options: ["Loyalty","Shared adventures","Emotional support","Independence"] },
  { id: 19, text: "You laugh hardest at:", options: ["Dry wit","Absurd chaos","Clever satire","Wholesome silliness"] },
  { id: 20, text: "You manage time by:", options: ["Planning everything","Prioritizing on the fly","Trusting your gut","Using tech tools"] },
  { id: 21, text: "Your dream space feels like:", options: ["Rustic and warm","Sleek and modern","Colorful and creative","Minimal and serene"] },
  { id: 22, text: "Your beliefs are shaped by:", options: ["Tradition","Exploration","Reflection","Logic"] },
  { id: 23, text: "You handle tension by:", options: ["Addressing it head-on","Mediating calmly","Reteating to think","Expressing emotions"] },
  { id: 24, text: "Your favorite kind of memory is:", options: ["Quiet peace","Shared laughter","Personal wins","Spontaneous adventures"] },
  { id: 25, text: "You feel most creative when:", options: ["Making with your hands","Solving puzzles","Telling stories","Rearranging your space"] },
];

export default QUESTIONS;
